services:
    app:
        build: .
        container_name: product-catalog-service
        ports:
            - "8000:8000"
        environment:
            - NODE_ENV=production
            - PORT=8000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DB_PATH=/app/data/database.sqlite
            - API_PREFIX=/api/v1
            - GEMINI_API_KEY=AIzaSyCcAKpmFbGcHKzdkiPbUB0FxgHnvH_fv_I
        volumes:
            - ./data:/app/data
        depends_on:
            - redis
        restart: unless-stopped
        networks:
            - snap-network

    redis:
        image: redis:7-alpine
        container_name: snap-redis
        ports:
            - "6380:6379"
        volumes:
            - redis_data:/data
        restart: unless-stopped
        networks:
            - snap-network
        command: redis-server --appendonly yes

volumes:
    redis_data:

networks:
    snap-network:
        driver: bridge
